name: Deploy Testimonials MFE to Google Cloud Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: dipeshsingh2012/shared-workflows/.github/workflows/deploy-mfe-gcs.yml@main
    with:
      dest_dir: 'mfes/testimonials-ui'
